package com.legstar.avro.cob2avro.samples;

import java.io.File;
import java.io.FileInputStream;

import org.apache.avro.Schema;

import com.legstar.avro.cob2avro.ZosVarRdwDatumReader;

import com.legstar.avro.beans.custdat.bind.CustomerDataBinding;
import com.legstar.avro.specific.custdat.CustomerData;


public class CustdatReader {

    // Avro schema for the Customer data record
    // Schema is generated by Cob2AvroTransGenerator
    private static final String AVRO_SHEMA_PATH = "gen/avsc/custdat.avsc";

    // Mainframe file on the file system
    // This one has a Record Descriptor Word (RDW) in front on each record
    private static final String ZOS_FILE_PATH = "data/ZOS.FCUSTDAT.RDW.bin";

    public static void main(final String[] args) throws Exception {

        Schema schema = new Schema.Parser().parse(new File(AVRO_SHEMA_PATH));

        File inFile = new File(ZOS_FILE_PATH);

        ZosVarRdwDatumReader < CustomerData > reader = new ZosVarRdwDatumReader < CustomerData >(
                new FileInputStream(inFile), inFile.length(), schema,
                new CustomerDataBinding());

        while (reader.hasNext()) {
            CustomerData avroRecord = reader.next();
            System.out
                .println("Record num="
                        + avroRecord.getCustomerId()
                        + ", customer name="
                        + avroRecord.getPersonalData().getCustomerName()
                        + ", transaction amount="
                        + (avroRecord.getTransactions().getTransaction()
                                .size() > 0 ? avroRecord.getTransactions()
                                .getTransaction().get(0)
                                .getTransactionAmount() : "none"));
        }

    }

}
